package MyLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_C1;
  private ConceptPresentation props_C2;
  private ConceptPresentation props_InternalC1;
  private ConceptPresentation props_InternalC2;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.C1:
        if (props_C1 == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_C1 = cpb.create();
        }
        return props_C1;
      case LanguageConceptSwitch.C2:
        if (props_C2 == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_C2 = cpb.create();
        }
        return props_C2;
      case LanguageConceptSwitch.InternalC1:
        if (props_InternalC1 == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InternalC1 = cpb.create();
        }
        return props_InternalC1;
      case LanguageConceptSwitch.InternalC2:
        if (props_InternalC2 == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InternalC2 = cpb.create();
        }
        return props_InternalC2;
    }
    return null;
  }
}
