package MyLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int C1 = 0;
  public static final int C2 = 1;
  public static final int InternalC1 = 2;
  public static final int InternalC2 = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb808eb8617bb451bL, 0x8c4657da0ebdf198L);
    builder.put(0x6b840e3fa27a1df6L, C1);
    builder.put(0x6b840e3fa27a1df7L, C2);
    builder.put(0x6b840e3fa27aa1b4L, InternalC1);
    builder.put(0x6b840e3fa27aa1b5L, InternalC2);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
