package MyLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptC1 = createDescriptorForC1();
  /*package*/ final ConceptDescriptor myConceptC2 = createDescriptorForC2();
  /*package*/ final ConceptDescriptor myConceptInternalC1 = createDescriptorForInternalC1();
  /*package*/ final ConceptDescriptor myConceptInternalC2 = createDescriptorForInternalC2();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptC1, myConceptC2, myConceptInternalC1, myConceptInternalC2);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.C1:
        return myConceptC1;
      case LanguageConceptSwitch.C2:
        return myConceptC2;
      case LanguageConceptSwitch.InternalC1:
        return myConceptInternalC1;
      case LanguageConceptSwitch.InternalC2:
        return myConceptInternalC2;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForC1() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MyLanguage", "C1", 0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27a1df6L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2bd6f2d4-8160-46e9-88ee-dc9b12ae24c8(MyLanguage.structure)/7747332925455736310");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForC2() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MyLanguage", "C2", 0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27a1df7L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2bd6f2d4-8160-46e9-88ee-dc9b12ae24c8(MyLanguage.structure)/7747332925455736311");
    b.version(2);
    b.associate("c1Ref", 0x6b840e3fa27a1df8L).target(0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27a1df6L).optional(true).origin("7747332925455736312").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInternalC1() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MyLanguage", "InternalC1", 0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27aa1b4L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2bd6f2d4-8160-46e9-88ee-dc9b12ae24c8(MyLanguage.structure)/7747332925455770036");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInternalC2() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MyLanguage", "InternalC2", 0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27aa1b5L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2bd6f2d4-8160-46e9-88ee-dc9b12ae24c8(MyLanguage.structure)/7747332925455770037");
    b.version(2);
    b.associate("c1ref", 0x6b840e3fa27c080eL).target(0xb808eb8617bb451bL, 0x8c4657da0ebdf198L, 0x6b840e3fa27aa1b4L).optional(true).origin("7747332925455861774").done();
    return b.create();
  }
}
